version: '3'

services:
  frontend:
    container_name: client-react
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/client
      - /client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - laravel

networks:
  laravel:
